### ISSUE TITLE
[feat] byes, leg bye, wide + runs

### ISSUE THREAD

**Issue by soham2k06** [soham2k06/cricket-scorer#54]

**Comment by rajeshmn47** [comment]
working on it

**Comment by soham2k06** [comment]
Ok great.

You can take a reference from no ball popover for wide plus runs

**Comment by rajeshmn47** [comment]
i have completed it,i want to confirm

**Comment by rajeshmn47** [comment]
https://www.awesomescreenshot.com/video/26854321?key=13f02efc8de6e2fa6f84863453498957

**Comment by soham2k06** [comment]
Nice add-ons for the application. Great usecase of popover

But It seemed that wide + single did not change a strike and also we can remove that -5 (might be for byes or lb)

**Comment by rajeshmn47** [comment]
https://www.awesomescreenshot.com/video/26873215?key=399f23bf0df39858a0df15eb0e5d1d5e

**Comment by rajeshmn47** [comment]
check this out

**Comment by rajeshmn47** [comment]
i am thinking every condition is covered here.Shall i raise the PR? 
https://www.awesomescreenshot.com/video/26889746?key=daa42bada988cdc29d48c03eda687720
