### ISSUE TITLE
[fix] deleting team error when any of it's player is deleted

### ISSUE THREAD

**Issue by soham2k06** [soham2k06/cricket-scorer#60]

**Comment by soham2k06** [comment]
Yes that is an actual bug.

When we create a team, it creates a new document named teamPlayer.

I needed to do that because mongodb does not support many to many
relationship

And possible fix is to also delete teamPlayer associated with player that
user is deleting

**Comment by rajeshmn47** [comment]
is it not possible to delete team?

**Comment by rajeshmn47** [comment]
see i was able to delete team

**Comment by rajeshmn47** [comment]
ok understood the bug

**Comment by rajeshmn47** [comment]
assign this to me

**Comment by soham2k06** [comment]
Just raise a pull request and I will merge it.

Right now I am outside home so I am unable to handle GitHub

I just have a tip that you just need to delete teamPlayer on api where we
are deleting the player, I guess it should work

**Comment by rajeshmn47** [comment]
is it fixed?

**Comment by soham2k06** [comment]
> is it fixed?

I tested in right now and it is working fine.

You want to contribute to other issues if you want
